### ISSUE TITLE
i working on you model

### ISSUE THREAD

**Issue by Roubish** [MuhammadMoinFaisal/FireDetectionYOLOv8#1]
hey I try to use your mode but gating some issues so can you help  me with some info regarding your mode. have you trained the custom model

**Comment by Roubish** [comment]
have you tried the custom mode for fireyolov8?

**Comment by MuhammadMoinFaisal** [comment]
Hi I have explained all the steps in very detail from start till end in my YouTube tutorial please watch If you have any issienyou can ask there in comment section i will surely help you out 

Thanks
